### ISSUE TITLE
Imagen desbordada en página de contacto.

### ISSUE THREAD

**Issue by hcinko5** [allan2sk/pypweb-modernizacion-pagina-web#1]
En la página de contacto contact-us.html, la imagen de banner se desborda por el lado derecho. También es de un tamaño muy pesado (400 KB  aprox.)

![screen shot 2015-03-12 at 7 01 40 pm](https://cloud.githubusercontent.com/assets/9490145/6631358/567bddde-c8ea-11e4-8a40-d808683991b9.png)
![screen shot 2015-03-12 at 7 01 52 pm](https://cloud.githubusercontent.com/assets/9490145/6631361/5944bea0-c8ea-11e4-8e9a-258e857566e5.png)
![screen shot 2015-03-12 at 7 02 03 pm](https://cloud.githubusercontent.com/assets/9490145/6631362/5b310f48-c8ea-11e4-8f13-0ff498ec97c0.png)

**Comment by luiscarranco** [comment]
Este issue ya fue resuelto eliminando la imágen y dejando solamente el formulario de contacto.
