### ISSUE TITLE
Menu con proporciones inadecuadas

### ISSUE THREAD

**Issue by hcinko5** [allan2sk/pypweb-modernizacion-pagina-web#10]
En el menú de "SERVICIOS Y PRODUCTOS" el menú drop-down se ve más pequeño que el menú superior, por lo cual se nota el borde inferior desproporcionado

![screen shot 2015-04-21 at 9 02 12 pm](https://cloud.githubusercontent.com/assets/9490145/7266073/ce87d14a-e869-11e4-823c-00bbbcfd2963.png)

**Comment by jdmonroyr** [comment]
Podrìamos considerar un nombre de secciòn mas corto para no romper con el estilo, algo como: "SW y Servicios" o algo similar

**Comment by jdmonroyr** [comment]
Se probaron en dispositivos móviles y se valida funcionalidad.

**Comment by luiscarranco** [comment]
Se deja como está ya que no representanta un problema grave, y el cambio del nombre podría no transmitir el mensaje adecuado
