### ISSUE TITLE
Página en Construcción Falta acento.

### ISSUE THREAD

**Issue by doncesarts** [allan2sk/pypweb-modernizacion-pagina-web#14]
Falta un acento en la palabra será, de la frase 

"Nuestra página "Eventos" sera publicada próximamente."

**Comment by jdmonroyr** [comment]
Se resuelve con HTML codes. La verdad no se que tan requeridos andan hoy en día los HTML Codes para los diferentes navegadores, ¿Tu sabes Chris? para ver si estandarizamos luego esa parte.
