### ISSUE TITLE
Oficinas

### ISSUE THREAD

**Issue by jdmonroyr** [allan2sk/pypweb-modernizacion-pagina-web#2]
En los textos de oficinas, modificar para nombrar primero a los visitantes, asociados de negocio y en últimas a los empleados de GAPSI.
![evidence_oficinas](https://cloud.githubusercontent.com/assets/2791686/6791760/411abcfe-d177-11e4-9582-825fa464b3b3.png)

**Comment by cgomezGAPSI** [comment]
Ya se modificó el orden según lo sugerido en este Issue.
