### ISSUE TITLE
Correcciones ortográficas en "Home"

### ISSUE THREAD

**Issue by luiscarranco** [allan2sk/pypweb-modernizacion-pagina-web#3]
- En Header, en menú nosotros, acento en "Quiénes"
- En segundo frame, donde se encuentra el botón de "Contáctanos", corregir "acompañamiento"
- En la sección "Nuestros servicios" eliminar acento en "o" en el rubro de "Cursos de Capacitación"
- En la sección "Nuestros servicios" eliminar acento en "o" en el rubro de "Servicios de Consultoría"
- En la sección "Nuestros servicios" eliminar acento en "o" y cambiar mayúscula a título en "Medida" en el rubro de "Desarrollo a la medida"
- En la sección "Verificación de licenciamiento", cambiar a mayúscula en el titulo "Licenciamiento"
- En el Footer, en la sección "Datos de contacto", cambiar a mayúscula "Contacto" en el título y corregir "Monterrrey" por "Monterrey"

**Comment by jdmonroyr** [comment]
Se solucionaron los issues y se subieron los cambios al repositorio. Luis favor valida los cambios para dar por cerrado este issue.

**Comment by luiscarranco** [comment]
Revisado y cerrado
