### ISSUE TITLE
Correcciones ortográficas en "Contáctanos"

### ISSUE THREAD

**Issue by luiscarranco** [allan2sk/pypweb-modernizacion-pagina-web#5]
- En el primer párrafo del formulario, corregir el texto: "Es muy importante tu opinión. Déjanos tus datos, dudas y comentarios y en breve te contactaremos."
- En el formulario, cambiar el texto "Email" por "E-mail"
- En la sección "Nuestras Oficinas", cambiar en todos los rubros donde aparezca "DF" por "D.F."
- Cambiar en la información de las tres sedes, en el rubro de horario de atención, por horas completas (9:00 am en lugar de 9am)

**Comment by jdmonroyr** [comment]
Resuelto, pendiente revisión.

**Comment by luiscarranco** [comment]
Revisado y cerrado
