### ISSUE TITLE
Correcciones ortográficas y de contenido en "Quiénes Somos"

### ISSUE THREAD

**Issue by luiscarranco** [allan2sk/pypweb-modernizacion-pagina-web#6]
- Cambiar el texto de introducción al siguiente: "Grupo de Asesores Profesionales en Servicios de Integración (GAPSI) es una empresa de consultoría en tecnología. De origen mexicano y con más de 10 años de experiencia en el mercado, GAPSI se especializa en integrar aplicaciones para llevar la información donde y como sea requerido para beneficio de los clientes."
- En la sección de "Historia", en el año 2012, cambiar a el texto "...Colombia, Ecuador y Perú, y además somos reconocidos...". Tambien cambiar el texto "...1er. lugar de ventas..." por "1er. lugar en ventas"
- En el año 2011, cambiar el texto "Suramérica" por "Sudamérica" o "America del Sur", al ser estos dos últimos más comúnmente utilizados (revisar Wikipedia)
- En el año 2010, cambiar el texto "...obtiene de parte de IBM el estatus..." y cambiar a "Premier Business Partner" tal como aparece en el logo

**Comment by jdmonroyr** [comment]
Resuelto, pendiente verificar.

**Comment by luiscarranco** [comment]
Revisado y cerrado. Muchas gracias.
