### ISSUE TITLE
Enlaces inactivos (Página "Próximamente")

### ISSUE THREAD

**Issue by luiscarranco** [allan2sk/pypweb-modernizacion-pagina-web#7]
A continuación se listan los enlaces que deben mostrar la página "Proximamente":

Desde el menú del Header:
- Opción "Reconocimientos" en el menú "Nosotros", CORRECTO
- Todas las opciones del menú "Servicios y Productos", CORRECTO
- Todas las opciones del menú "Experiencia", CORRECTO
- Menú "Unete al equipo", CORREGIR
- DECIDIR QUÉ APARECERÁ EN LAS OPCIONES DE FAQ Y MAPA DEBAJO DEL FOOTER

**Comment by jdmonroyr** [comment]
Pendiente validación.

**Comment by luiscarranco** [comment]
Estoy de acuerdo, solo quedaría pendiente definir el texto de la página de próximamente, para la cual enviaré en este momento una propuesta vía correo.
Se cerrará este "issue"
