### ISSUE TITLE
Submenus en menu para dispositivos móviles 

### ISSUE THREAD

**Issue by jdmonroyr** [allan2sk/pypweb-modernizacion-pagina-web#8]
Las secciones de submenu no se están desplegando cuando se da clic sobre ellas cuando el menu se encuentra compactado en modo mobile.
Probablemente debe ser alguna clase de css que eliminamos o algún cambio que hicimos en el header.
![issue 8](https://cloud.githubusercontent.com/assets/2791686/7192364/5b3e6ba8-e45a-11e4-9ae6-907b907e155f.png)

**Comment by jdmonroyr** [comment]
El issue se presenta debido a la carga del menu mediante un archivo externo. Se realizò la prueba y cuando el header se encuentra en el mismo archivo funciona normalmente. Como alternativas se probò con la funciòn .load() y .append() con los mismos resultados. Temporalemente se incluyo el header en index.html para poder realizar las pruebas en mòviles.

**Comment by hcinko5** [comment]
Se agrega corrección en último commit. Por favor realicen las pruebas pertinentes.

**Comment by jdmonroyr** [comment]
Se realizaron las pruebas en dispositivos móviles y se valido la fiuncionalidad.
