### ISSUE TITLE
Propuesta texto página "Próximamente"

### ISSUE THREAD

**Issue by luiscarranco** [allan2sk/pypweb-modernizacion-pagina-web#9]
Para esta página, propongo el siguiente texto:
- En lugar de "Nuestro nuevo sitio web sera publicado próximamente" propongo "Esta sección del sitio web se encuentra en construcción"
- El texto "Estamos trabajando para ofrecerte una mejor experiencia de usuario." ponerlo en un color más obscuro para que no se pierda
- El texto "En breve toda la información sobre nuestra compañía estará disponible." se queda
- Las barras con los porcentajes creo que están bien, y no veo necesario estar actualizando los porcentajes, solo es algo representativo y diferente
- No se si en el catálogo del template venga alguna imagen que podamos agregar a un costado de las barras de porcentaje, para que no se vea tan... plano, algo como ésto:

![coming-soonsp](https://cloud.githubusercontent.com/assets/11047580/7242556/20021ea4-e789-11e4-8235-74243b6a190f.png)

Quedo en espera de sus comentarios.

**Comment by jdmonroyr** [comment]
Se realizaron los cambios sugeridos. Pendiente revisar el tema de la imagen.

**Comment by jdmonroyr** [comment]
Se deja el comentario de incluir alguna imágen como "Nice to have" para próximos sprints.
